# Generated by Django 5.1.5 on 2026-02-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                ("dbname", models.CharField(max_length=128)),
                ("user", models.CharField(max_length=128)),
                ("password_enc", models.BinaryField()),
                ("ssl_mode", models.CharField(default="prefer", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("details", models.TextField()),
                ("sql", models.TextField(blank=True)),
                ("confidence", models.CharField(max_length=16)),
                ("score", models.FloatField(default=0)),
                ("fingerprint", models.CharField(max_length=128)),
                ("status", models.CharField(default="open", max_length=32)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.instance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetupState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pg_version_num", models.IntegerField(null=True)),
                ("preload_ok", models.BooleanField(default=False)),
                ("ext_created", models.BooleanField(default=False)),
                ("ready", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.instance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.instance"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queryid", models.CharField(max_length=128)),
                ("query_norm", models.TextField()),
                ("calls", models.BigIntegerField(default=0)),
                ("total_time_ms", models.FloatField(default=0)),
                ("mean_time_ms", models.FloatField(default=0)),
                ("rows", models.BigIntegerField(default=0)),
                ("shared_blks_read", models.BigIntegerField(default=0)),
                ("shared_blks_hit", models.BigIntegerField(default=0)),
                ("temp_blks_written", models.BigIntegerField(default=0)),
                ("wal_bytes", models.BigIntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_stats",
                        to="core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queryid", models.CharField(max_length=128)),
                ("last_explained_at", models.DateTimeField(auto_now=True)),
                ("explain_json", models.JSONField()),
                ("features_json", models.JSONField()),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.instance"
                    ),
                ),
            ],
            options={
                "unique_together": {("queryid", "instance")},
            },
        ),
    ]
